#!/usr/bin/env python3
"""Fetch an NFL regular-season schedule from ESPN's public scoreboard API.

    python3 tools/fetch_schedule.py 2026 --out data/2026-schedule.json

Same keyless endpoint the tracker's fetch_results.py uses, and the same week
mapping (seasontype 2 = regular season, weeks 1-18). Only the regular season is
fetched: the postseason bracket is simulated, not scheduled.

Output is keyed by NFL nickname exactly as ESPN spells it, so it lines up with
js/vendor/nfl-teams.js without a translation table.

Python 3 stdlib only, so this runs unmodified in a GitHub Action.
"""

import argparse
import json
import os
import sys
import urllib.request
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _emit import write_module

API = "https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard"
REGULAR_SEASON = 2
WEEKS = 18


def fetch(season, week, cache_dir):
    url = f"{API}?dates={season}&seasontype={REGULAR_SEASON}&week={week}"
    path = None
    if cache_dir:
        os.makedirs(cache_dir, exist_ok=True)
        path = os.path.join(cache_dir, f"sched_{season}_w{week}.json")
        if os.path.exists(path):
            with open(path) as fh:
                return json.load(fh)
    with urllib.request.urlopen(url, timeout=30) as resp:
        payload = json.load(resp)
    if path:
        with open(path, "w") as fh:
            json.dump(payload, fh)
    return payload


def games_for_week(payload):
    """[{home, away}] for every scheduled game in the week."""
    out = []
    for event in payload.get("events", []):
        for competition in event.get("competitions", []):
            competitors = competition.get("competitors", [])
            if len(competitors) != 2:
                continue
            sides = {c.get("homeAway"): c["team"]["name"] for c in competitors}
            if "home" not in sides or "away" not in sides:
                # Neutral-site games still carry a nominal home/away in this feed.
                # If that ever stops being true, say so rather than guessing.
                print(f"  WARNING: game without home/away: {sides}", file=sys.stderr)
                continue
            out.append({"home": sides["home"], "away": sides["away"]})
    return out


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("season", type=int)
    parser.add_argument("--out", required=True)
    parser.add_argument("--cache", default=None)
    args = parser.parse_args()

    weeks = {}
    for week in range(1, WEEKS + 1):
        try:
            payload = fetch(args.season, week, args.cache)
        except Exception as exc:  # noqa: BLE001 - report and keep going
            print(f"  week {week}: fetch failed ({exc})", file=sys.stderr)
            continue
        games = games_for_week(payload)
        weeks[str(week)] = games
        print(f"  week {week}: {len(games)} games")

    # Sanity checks. These are reported, never silently repaired.
    problems = []
    counts = {}
    for week, games in weeks.items():
        for game in games:
            for team in (game["home"], game["away"]):
                counts[team] = counts.get(team, 0) + 1
    if len(counts) != 32:
        problems.append(f"expected 32 teams, saw {len(counts)}")
    for team, played in sorted(counts.items()):
        if played != 17:
            problems.append(f"{team} has {played} games, expected 17")
    for week, games in sorted(weeks.items(), key=lambda kv: int(kv[0])):
        seen = [t for g in games for t in (g["home"], g["away"])]
        if len(seen) != len(set(seen)):
            problems.append(f"week {week}: a team appears twice")

    doc = {
        "season": args.season,
        "updated": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "weeks": weeks,
        "problems": problems,
    }
    write_module(args.out, doc, header=(
        f"{args.season} NFL regular-season schedule, from ESPN's public scoreboard API.\n"
        "Generated by tools/fetch_schedule.py. Do not hand-edit."))

    print(f"wrote {args.out}")
    if problems:
        print(f"\n{len(problems)} PROBLEM(S) — recorded in the file, not fixed:", file=sys.stderr)
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        return 1
    print("schedule passes all sanity checks (32 teams, 17 games each, no double-bookings)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
